### ISSUE TITLE
Replacement of words.eng list

### ISSUE THREAD

**Issue by chamin69** [idmn/wfindr#5]
Is it possible the replacement of words.eng list with a user's vector?

**Comment by idmn** [comment]
You can use your dictionary by passing it to the `words` parameter. E.g.:
```r
library(wfindr)
my_dict <- c("banana", "potato")
find_word(".a.a.a", words = my_dict)
#> [1] "banana"
```

**Comment by chamin69** [comment]
Many thanks for the answer!

Στις Κυρ, 3 Μαΐ 2020 στις 2:40 μ.μ., ο/η Iaroslav Domin <
notifications@github.com> έγραψε:
